site_name: ch3ddr – Privacy Policies
site_url: https://ch3ddr.github.io/privacy/
site_description: Privacy Policies for apps by ch3ddr

theme:
  name: material
  palette:
    scheme: slate
    primary: black
    accent: deep orange
  features:
    - navigation.instant
    - navigation.top

nav:
  - Home: index.md
  - The Cage: the-cage.md
  - Account Deletion: delete-account.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
